### ISSUE TITLE
2020.2.6 Java学习笔记 | ARUKI'S BLOG

### ISSUE THREAD

**Issue by korilin** [korilin/korilin#31]
https://www.arukione.com/2020/02/06/2020.2.6%20Java%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/ 

 用树结构获取自然数拆分结果 | ARUKI'S BLOG

**Comment by 6yi** [comment]
lambda表达式
```java

      ilist.forEach(h->{
            System.out.println(h);
        });

```
