### ISSUE TITLE
关于hexo的

### ISSUE THREAD

**Issue by Mr-ind1fferent** [korilin/korilin#65]
在hexo上看到了你的主题，想用一下，请问如何使用

**Comment by korilin** [comment]
hexo 上的是这个项目，<https://github.com/korilin/hexo-theme-particle>
目前我自己已经没使用 hexo 了，用的是 vuepress，但是那个主题的样式部署还在，你可以进入那个仓库访问一下看看效果。相关说明在那里也有写。
